name: Deploy Frontend to GitHub Pages
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # ◄ REQUIRED: Uses official checkout action

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # ◄ REQUIRED: Deployment action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # ◄ Points to your frontend files
