name: Deploy Frontend
on:
  push:
    branches: [main]

# Minimal required permissions
permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # New: Install dependencies if needed (e.g., npm ci)
      - name: Install dependencies
        run: |
          cd docs
          [ -f package.json ] && npm ci || echo "No dependencies to install"

      # Uses GitHub's native Pages deployment
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'  # Your frontend directory
          # Optional: exclude README.md from deployment
          exclude: 'README.md'  

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
